changelog:
  exclude:
    authors:
      - github-actions[bot]
    labels:
      - skip-changelog
  categories:
    - title: Features
      labels:
        - feat
        - feature
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Documentation
      labels:
        - docs
    - title: Infra
      labels:
        - infra
        - ci
        - cd
        - devops
